version: 0.2

phases:
  pre-build:
    commands:
      - echo Logging in to AWS ECR
      - aws --version 
      - aws ecr get-login-password --region us-eats-1 | docker login --username
        AWS --password-stdin 702453143343.dkr.ecr.us-east-1.amazonaws.com/grouperp
      - REPOSITORY_URI=702453143343.dkr.ecr.us-east-1.amazonaws.com/grouperp
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the docker image
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post-build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker image
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG 
      
artifacts:
  files:
    - "Dockerrun.aws.json"